name: gg_json
description: gg_json offers a bunch of JSON helpers used in various context.
version: 3.0.13
repository: https://github.com/inlavigo/gg_json.git

environment:
  sdk: ">=3.10.7 <4.0.0"

dev_dependencies:
  gg_test_matchers: ^1.1.0
  lints: ^6.0.0
  test: ^1.24.0